[package]
name = "anny-dock-slint"
version = "0.0.1"
edition = "2021"

[build-dependencies]
slint-build = "1.4.1"

[dependencies]
slint = "1.4.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
image = "0.24"
bytemuck = "1.0"
