[package]
name = "pdock"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk4 = { version = "0.7", features = ["v4_6"] }
glib = "0.17"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
once_cell = "1.19"
